// AUTO-GENERATED by scripts/import-market.mjs from data/market-input.csv.
// Do not edit by hand — edit the CSV and re-run `node scripts/import-market.mjs`.
import type { MarketArea } from "@/types";

export const marketData: Record<string, MarketArea> = {
  "nepa": {
    "metrics": {
      "medianPrice": {
        "value": 219000,
        "change": "+3.1%",
        "trend": "up"
      },
      "homesForSale": {
        "value": 1240,
        "change": "-2.4%",
        "trend": "down"
      },
      "daysOnMarket": {
        "value": 38,
        "change": "+5 days",
        "trend": "up"
      },
      "saleToList": {
        "value": 98.6,
        "change": "+0.4%",
        "trend": "up"
      }
    },
    "source": "Sample data",
    "asOf": "2026-08-01",
    "isSample": true
  },
  "wilkes-barre-pa": {
    "metrics": {
      "medianPrice": {
        "value": 168000
      },
      "homesForSale": {
        "value": 240
      },
      "daysOnMarket": {
        "value": 41
      },
      "saleToList": {
        "value": 98.2
      }
    },
    "source": "Sample data",
    "asOf": "2026-08-01",
    "isSample": true
  },
  "scranton-pa": {
    "metrics": {
      "medianPrice": {
        "value": 179000
      },
      "homesForSale": {
        "value": 310
      },
      "daysOnMarket": {
        "value": 36
      },
      "saleToList": {
        "value": 99
      }
    },
    "source": "Sample data",
    "asOf": "2026-08-01",
    "isSample": true
  },
  "pittston-pa": {
    "metrics": {
      "medianPrice": {
        "value": 172000
      },
      "homesForSale": {
        "value": 95
      },
      "daysOnMarket": {
        "value": 39
      },
      "saleToList": {
        "value": 98.5
      }
    },
    "source": "Sample data",
    "asOf": "2026-08-01",
    "isSample": true
  },
  "kingston-pa": {
    "metrics": {
      "medianPrice": {
        "value": 189000
      },
      "homesForSale": {
        "value": 120
      },
      "daysOnMarket": {
        "value": 34
      },
      "saleToList": {
        "value": 99.1
      }
    },
    "source": "Sample data",
    "asOf": "2026-08-01",
    "isSample": true
  },
  "dallas-pa": {
    "metrics": {
      "medianPrice": {
        "value": 285000
      },
      "homesForSale": {
        "value": 85
      },
      "daysOnMarket": {
        "value": 45
      },
      "saleToList": {
        "value": 98
      }
    },
    "source": "Sample data",
    "asOf": "2026-08-01",
    "isSample": true
  },
  "hazleton-pa": {
    "metrics": {
      "medianPrice": {
        "value": 149000
      },
      "homesForSale": {
        "value": 175
      },
      "daysOnMarket": {
        "value": 43
      },
      "saleToList": {
        "value": 97.8
      }
    },
    "source": "Sample data",
    "asOf": "2026-08-01",
    "isSample": true
  },
  "nanticoke-pa": {
    "metrics": {
      "medianPrice": {
        "value": 142000
      },
      "homesForSale": {
        "value": 70
      },
      "daysOnMarket": {
        "value": 40
      },
      "saleToList": {
        "value": 98.1
      }
    },
    "source": "Sample data",
    "asOf": "2026-08-01",
    "isSample": true
  },
  "mountain-top-pa": {
    "metrics": {
      "medianPrice": {
        "value": 265000
      },
      "homesForSale": {
        "value": 60
      },
      "daysOnMarket": {
        "value": 44
      },
      "saleToList": {
        "value": 98.3
      }
    },
    "source": "Sample data",
    "asOf": "2026-08-01",
    "isSample": true
  },
  "clarks-summit-pa": {
    "metrics": {
      "medianPrice": {
        "value": 255000
      },
      "homesForSale": {
        "value": 55
      },
      "daysOnMarket": {
        "value": 38
      },
      "saleToList": {
        "value": 99
      }
    },
    "source": "Sample data",
    "asOf": "2026-08-01",
    "isSample": true
  },
  "plains-pa": {
    "metrics": {
      "medianPrice": {
        "value": 175000
      },
      "homesForSale": {
        "value": 80
      },
      "daysOnMarket": {
        "value": 37
      },
      "saleToList": {
        "value": 98.7
      }
    },
    "source": "Sample data",
    "asOf": "2026-08-01",
    "isSample": true
  },
  "forty-fort-pa": {
    "metrics": {
      "medianPrice": {
        "value": 182000
      },
      "homesForSale": {
        "value": 45
      },
      "daysOnMarket": {
        "value": 33
      },
      "saleToList": {
        "value": 99.3
      }
    },
    "source": "Sample data",
    "asOf": "2026-08-01",
    "isSample": true
  },
  "wyoming-pa": {
    "metrics": {
      "medianPrice": {
        "value": 178000
      },
      "homesForSale": {
        "value": 50
      },
      "daysOnMarket": {
        "value": 35
      },
      "saleToList": {
        "value": 99
      }
    },
    "source": "Sample data",
    "asOf": "2026-08-01",
    "isSample": true
  }
};
