#!/usr/bin/env node
/**
 * Fetch monthly market HISTORY from Zillow Research public CSVs and generate
 * data/market-history.ts (the time series behind the city market charts).
 *
 *   npm run market:history            # last 60 months (default)
 *   npm run market:history -- --months 36
 *
 * Covers the Scranton–Wilkes-Barre metro (-> nepa) and the larger cities Zillow
 * publishes at city level. Cities without their own series fall back to the
 * regional series in the chart, clearly labeled. This is free public data — no
 * MLS/IDX required. Zillow occasionally renames files; if a feed 404s, update
 * the CONFIG below.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { parseCsv } from "./market-io.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "data", "market-history.ts");
const BASE = "https://files.zillowstatic.com/research/public_csvs";

const monthsArg = process.argv.indexOf("--months");
const MONTHS = monthsArg >= 0 ? Number(process.argv[monthsArg + 1]) || 60 : 60;

// chart metric -> Zillow directory (files are <dir>/<Level>_<dir>_uc_sfrcondo_month.csv)
const FEEDS = {
  medianPrice: "median_sale_price",
  homesSold: "sales_count_now",
  daysOnMarket: "med_doz_pending",
  inventory: "invt_fs",
};

const REGION_MAP = {
  nepa: { level: "Metro", name: "Scranton, PA" },
  "scranton-pa": { level: "City", name: "Scranton" },
  "wilkes-barre-pa": { level: "City", name: "Wilkes-Barre" },
  "hazleton-pa": { level: "City", name: "Hazleton" },
  "kingston-pa": { level: "City", name: "Kingston" },
  "pittston-pa": { level: "City", name: "Pittston" },
  "nanticoke-pa": { level: "City", name: "Nanticoke" },
};

const url = (dir, level) => `${BASE}/${dir}/${level}_${dir}_uc_sfrcondo_month.csv`;

async function fetchCsv(u) {
  const r = await fetch(u, { signal: AbortSignal.timeout(25000) });
  if (!r.ok) throw new Error(`${r.status} ${u}`);
  return parseCsv(await r.text());
}

/** Extract the last `MONTHS` {d:"YYYY-MM", v} points from a data row. */
function seriesFrom(header, row) {
  const pts = [];
  for (let i = 0; i < header.length; i++) {
    const h = (header[i] || "").trim();
    if (!/^\d{4}-\d{2}-\d{2}$/.test(h)) continue;
    const v = Number(row[i]);
    if (row[i] !== "" && Number.isFinite(v)) pts.push({ d: h.slice(0, 7), v: Math.round(v) });
  }
  return pts.slice(-MONTHS);
}

const areasData = {};
let latestMonth = "";
let feedErrors = 0;

for (const [metric, dir] of Object.entries(FEEDS)) {
  for (const level of ["Metro", "City"]) {
    const areas = Object.entries(REGION_MAP).filter(([, m]) => m.level === level);
    if (!areas.length) continue;
    let rows;
    try {
      rows = await fetchCsv(url(dir, level));
    } catch (e) {
      console.warn(`  ! ${metric} (${level}): ${e.message}`);
      feedErrors++;
      continue;
    }
    const header = rows[0];
    const nameCol = header.indexOf("RegionName");
    const stateCol = header.indexOf("StateName");
    for (const [slug, m] of areas) {
      const match = rows.find(
        (r) => r[nameCol] === m.name && (level === "Metro" || stateCol < 0 || r[stateCol] === "PA"),
      );
      if (!match) continue;
      const series = seriesFrom(header, match);
      if (series.length < 2) continue;
      (areasData[slug] ??= {})[metric] = series;
      const last = series[series.length - 1].d;
      if (!latestMonth || last > latestMonth) latestMonth = last;
    }
  }
}

if (Object.keys(areasData).length === 0) {
  console.error("No history fetched — check CONFIG URLs.");
  process.exit(1);
}

const banner =
  "// AUTO-GENERATED by scripts/fetch-history.mjs from Zillow Research public CSVs.\n" +
  "// Do not edit by hand — re-run `npm run market:history`.\n";
const body =
  banner +
  'import type { MarketHistory } from "@/types";\n\n' +
  `export const marketHistorySource = "Zillow Research";\n` +
  `export const marketHistoryAsOf = "${latestMonth}";\n\n` +
  "export const marketHistory: Record<string, MarketHistory> = " +
  JSON.stringify(areasData) +
  ";\n";
writeFileSync(OUT, body);

const areas = Object.keys(areasData);
console.log(`Wrote ${OUT}`);
console.log(`${areas.length} area(s), through ${latestMonth}, ${MONTHS}-month window; ${feedErrors} feed error(s).`);
for (const a of areas) console.log(`  ${a}: ${Object.keys(areasData[a]).join(", ")}`);
