#!/usr/bin/env node
/**
 * Market-data importer.
 *
 * Reads data/market-input.csv (the simple monthly sheet you fill from a public
 * source such as Zillow Research or Redfin's Data Center) and regenerates
 * data/market-data.ts, which the app reads through lib/market.ts.
 *
 * Usage:  node scripts/import-market.mjs
 *
 * Behaviour:
 *   - Values are stored raw (numbers); the app formats them for display.
 *   - `trend` is derived from the sign of each change column ("+" -> up,
 *     "-" -> down, otherwise flat).
 *   - An area is marked isSample=true only when its `source` is blank or begins
 *     with "sample". Fill in a real source (e.g. "Zillow Research") and that
 *     area's "Sample Data" badge automatically becomes real attribution.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const INPUT = join(root, "data", "market-input.csv");
const OUTPUT = join(root, "data", "market-data.ts");

const METRIC_KEYS = ["medianPrice", "homesForSale", "daysOnMarket", "saleToList"];

/** Minimal CSV parser: handles quoted fields and commas inside quotes. */
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++; }
      else if (c === '"') inQuotes = false;
      else field += c;
    } else if (c === '"') inQuotes = true;
    else if (c === ",") { row.push(field); field = ""; }
    else if (c === "\n" || c === "\r") {
      if (c === "\r" && text[i + 1] === "\n") i++;
      row.push(field); field = "";
      if (row.some((v) => v.trim() !== "")) rows.push(row);
      row = [];
    } else field += c;
  }
  if (field !== "" || row.length) { row.push(field); if (row.some((v) => v.trim() !== "")) rows.push(row); }
  return rows;
}

function trendFromChange(change) {
  const t = change.trim();
  if (!t) return undefined;
  if (t.startsWith("+")) return "up";
  if (t.startsWith("-")) return "down";
  return "flat";
}

const raw = readFileSync(INPUT, "utf8");
const [header, ...lines] = parseCsv(raw);
const col = Object.fromEntries(header.map((h, i) => [h.trim(), i]));

const areas = {};
for (const line of lines) {
  const get = (name) => (col[name] != null ? (line[col[name]] ?? "").trim() : "");
  const area = get("area");
  if (!area) continue;

  const metrics = {};
  for (const key of METRIC_KEYS) {
    const rawValue = get(key);
    if (rawValue === "") continue;
    const value = Number(rawValue);
    if (!Number.isFinite(value)) {
      throw new Error(`Non-numeric ${key} for area "${area}": "${rawValue}"`);
    }
    const change = get(`${key}_change`);
    metrics[key] = { value, ...(change ? { change, trend: trendFromChange(change) } : {}) };
  }

  const source = get("source") || "Sample data";
  const isSample = /^sample/i.test(source);
  areas[area] = {
    metrics,
    source,
    ...(get("sourceUrl") ? { sourceUrl: get("sourceUrl") } : {}),
    asOf: get("asOf") || "2026-08-01",
    isSample,
  };
}

if (!areas.nepa) {
  throw new Error('market-input.csv must include a "nepa" (regional) row.');
}

const banner =
  "// AUTO-GENERATED by scripts/import-market.mjs from data/market-input.csv.\n" +
  "// Do not edit by hand — edit the CSV and re-run `node scripts/import-market.mjs`.\n";
const body =
  banner +
  'import type { MarketArea } from "@/types";\n\n' +
  "export const marketData: Record<string, MarketArea> = " +
  JSON.stringify(areas, null, 2) +
  ";\n";

writeFileSync(OUTPUT, body);

const total = Object.keys(areas).length;
const real = Object.values(areas).filter((a) => !a.isSample).length;
console.log(`Wrote ${OUTPUT}`);
console.log(`${total} areas (${real} real, ${total - real} sample).`);
